# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudMessage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudMessage
  pod 'Firebase/Messaging'

  target 'NotificationServiceExtension' do
  inherit! :search_paths
  end

end
